# Generated by Django 5.0.1 on 2024-01-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_nickname", models.CharField(max_length=25)),
                ("user_mail", models.EmailField(max_length=255)),
            ],
        ),
    ]
